// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Episode defines model for Episode.
type Episode struct {
	// Author Episode author
	Author *string `json:"author,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Description Episode description
	Description string `json:"description"`

	// DurationSecs Duration in seconds
	DurationSecs int `json:"duration_secs"`

	// FileName Original file name
	FileName string `json:"file_name"`

	// FileSize File size in bytes
	FileSize int `json:"file_size"`

	// MimeType MIME type
	MimeType string `json:"mime_type"`

	// PubDate Publication date
	PubDate time.Time `json:"pub_date"`

	// Title Episode title
	Title string `json:"title"`

	// Uuid Unique identifier
	Uuid uuid.UUID `json:"uuid"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code string `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// GetV1EpisodesParams defines parameters for GetV1Episodes.
type GetV1EpisodesParams struct {
	// Limit Maximum number of episodes to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of episodes to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostV1EpisodesMultipartBody defines parameters for PostV1Episodes.
type PostV1EpisodesMultipartBody struct {
	// Author Episode author
	Author *string `json:"author,omitempty"`

	// Description Episode description (required)
	Description string `json:"description"`

	// File Audio file (required)
	File openapi_types.File `json:"file"`

	// PubDate Publication date
	PubDate *time.Time `json:"pub_date,omitempty"`

	// Title Episode title
	Title *string `json:"title,omitempty"`
}

// PostV1EpisodesMultipartRequestBody defines body for PostV1Episodes for multipart/form-data ContentType.
type PostV1EpisodesMultipartRequestBody PostV1EpisodesMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Redirect to RSS feed
	// (GET /)
	GetRoot(w http.ResponseWriter, r *http.Request)
	// Get iTunes-compatible RSS feed
	// (GET /feed.xml)
	GetFeedXml(w http.ResponseWriter, r *http.Request)
	// Serve audio file
	// (GET /files/{uuid})
	GetFilesByUuid(w http.ResponseWriter, r *http.Request, uuid uuid.UUID)
	// List all podcast episodes
	// (GET /v1/episodes)
	GetV1Episodes(w http.ResponseWriter, r *http.Request, params GetV1EpisodesParams)
	// Upload a new podcast episode
	// (POST /v1/episodes)
	PostV1Episodes(w http.ResponseWriter, r *http.Request)
	// Delete a podcast episode
	// (DELETE /v1/episodes/{uuid})
	DeleteV1EpisodesUuid(w http.ResponseWriter, r *http.Request, uuid uuid.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Redirect to RSS feed
// (GET /)
func (_ Unimplemented) GetRoot(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get iTunes-compatible RSS feed
// (GET /feed.xml)
func (_ Unimplemented) GetFeedXml(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Serve audio file
// (GET /files/{uuid})
func (_ Unimplemented) GetFilesByUuid(w http.ResponseWriter, r *http.Request, uuid uuid.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all podcast episodes
// (GET /v1/episodes)
func (_ Unimplemented) GetV1Episodes(w http.ResponseWriter, r *http.Request, params GetV1EpisodesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload a new podcast episode
// (POST /v1/episodes)
func (_ Unimplemented) PostV1Episodes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a podcast episode
// (DELETE /v1/episodes/{uuid})
func (_ Unimplemented) DeleteV1EpisodesUuid(w http.ResponseWriter, r *http.Request, uuid uuid.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetRoot operation middleware
func (siw *ServerInterfaceWrapper) GetRoot(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoot(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFeedXml operation middleware
func (siw *ServerInterfaceWrapper) GetFeedXml(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFeedXml(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFilesByUuid operation middleware
func (siw *ServerInterfaceWrapper) GetFilesByUuid(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid uuid.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFilesByUuid(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1Episodes operation middleware
func (siw *ServerInterfaceWrapper) GetV1Episodes(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1EpisodesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1Episodes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV1Episodes operation middleware
func (siw *ServerInterfaceWrapper) PostV1Episodes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1Episodes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteV1EpisodesUuid operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1EpisodesUuid(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid uuid.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteV1EpisodesUuid(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/", wrapper.GetRoot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/feed.xml", wrapper.GetFeedXml)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/files/{uuid}", wrapper.GetFilesByUuid)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/episodes", wrapper.GetV1Episodes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/episodes", wrapper.PostV1Episodes)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/episodes/{uuid}", wrapper.DeleteV1EpisodesUuid)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXW28bNxP9KwS/76Et1pHUOC96qxMnDeC0ri9FgcAwqOWsPMnyYl4cq4b+ezHclfYq",
	"qy7S1C/CaskZnpkzczj7wHOjrNGgg+fzB+7zG1AiPR5b9EYCPVpnLLiAkBZEDDfG0ZMEnzu0AY3m840B",
	"q9czHlYW+Jz74FAv+TrjuQMRQF6LMLR+TWtoNAuowAehLM94YZyizVyKAAe0Mua242gXqvbbMR/RpeOv",
	"PeR+6OVNvcxQMw+50dI3XlAHWIIjNwWWcK2FgqGLXx0uUYuS0R6W9ozgSA48/jni4C3Z0RKBWKwCjENQ",
	"qOC6et338OH9h2OWlkZOtnFxTWkemp3GRYl5FX/a8XeJCRhK2E1JtTxiFyPKodmlxtsIDCXogAWCa+NI",
	"JgNX64w7uI3oQPL5x+2m+txuSWzjb7PYJqSd2n7BdGr7aovDLD5BHiikY+eqnun2Ul53WC9BtJmltZHs",
	"KPBeLHeabZb3JaN2v9k+BE0GqAszPOjni4tT5sHdgWPBMCW0WAKzRubCBwYVvZ59wXDDRJRoWLSlETJj",
	"EkoIkLESfcjY+W8nGIApCEKKIJgF59EH0DlktWFqFjoK9TJjQkuGF1GDPyDdEgEXJbBJASBf3Ktyy+2c",
	"vzPstMZzdn7OjkT+GTSRf0dnpCjuZpRNY0ELi3zOX76YvphRIYhwk8iZ0M8SklgRaYnv95K8QzgzJnDK",
	"qLdG+4rNl9PZSPeAU4IEljmQ6CAPlLM25hsQElzycGKqPmu0mJ7gXiibwuqE2qM3EeajUsKt+JyftU6j",
	"FJBlKoLGxyPhvQWQf6RjOhH+OJ1WZasD6GQprN2Iw6T22QAfQOyJNe8Aa7C/gzDCcy8KLMFPHqin149G",
	"QvuOVpdV71vhhIKQ0v3xgSOBIMJ5xivZ3ohE0yrBRchaQe3TnKv9OaPSnvzQzdXW7QI1ZSHbn72fti1C",
	"lXw4PXyEm0++X1X/d1DwOf/fpBkBJvX9P6nkauTIdAlpE1hhou7Tdk6S0Grciqi72WQjCY/x9PvseLNr",
	"QFPvGhP3qKJiOqoFOGaKRnKCYQ5CdCToidvbCCmXNbklKqS2bbIgoRCxDHw+m2ZcVZ7pD/1DXf8b3rPr",
	"rI/ql1E0/jPaHVhMUXjYAaZ9+nTk9Ksn9eWQewyg/N4iqCfA9RaAcE6sxsriBH1oh042r56I6R/V43sd",
	"wNFUVV9HUG9sl2UCJ8pycEOlscf4kXo8Nb5bkCQH4MORkateUCqWAa1wYUIdfEAXWTeurzU9P3XMZd9t",
	"NOz7XZPm0E8jKV3zver0jAbI3qDTHfNS2GPDznrQUrOvV76bThoW8CaWen5kPuY5eF/EslxVqv4NuuhI",
	"SFZXODtgCr1HvazSy4xjqO9EiZKhtjFNs4ezV/8+qEvto7XGUVYUSBTp04UdbOGkKk08Pie1uUyjLhNM",
	"w5e+4gwuxNb8Uo3GQyl6k943YvRfDjKHjwkPwRyr328wlWxAtAaTZ1QRFYNMjFQD7UuGY3PO6+gcfTdU",
	"O3jGoyvpG4Cvr9Z/BQAA///5iAL4uREAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
