// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Episode defines model for Episode.
type Episode struct {
	// Author Episode author
	Author *string `json:"author,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Description Episode description
	Description string `json:"description"`

	// DurationSecs Duration in seconds
	DurationSecs *int `json:"duration_secs,omitempty"`

	// FileName Original file name
	FileName string `json:"file_name"`

	// FileSize File size in bytes
	FileSize int `json:"file_size"`

	// MimeType MIME type
	MimeType string `json:"mime_type"`

	// PubDate Publication date
	PubDate time.Time `json:"pub_date"`

	// Title Episode title
	Title string `json:"title"`

	// Uuid Unique identifier
	Uuid openapi_types.UUID `json:"uuid"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code string `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// GetV1EpisodesParams defines parameters for GetV1Episodes.
type GetV1EpisodesParams struct {
	// Limit Maximum number of episodes to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of episodes to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostV1EpisodesMultipartBody defines parameters for PostV1Episodes.
type PostV1EpisodesMultipartBody struct {
	// Author Episode author
	Author *string `json:"author,omitempty"`

	// Description Episode description (required)
	Description string `json:"description"`

	// File Audio file (required)
	File openapi_types.File `json:"file"`

	// PubDate Publication date
	PubDate *time.Time `json:"pub_date,omitempty"`

	// Title Episode title
	Title *string `json:"title,omitempty"`
}

// PostV1EpisodesMultipartRequestBody defines body for PostV1Episodes for multipart/form-data ContentType.
type PostV1EpisodesMultipartRequestBody PostV1EpisodesMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Redirect to RSS feed
	// (GET /)
	GetRoot(w http.ResponseWriter, r *http.Request)
	// Get iTunes-compatible RSS feed
	// (GET /feed.xml)
	GetFeedXml(w http.ResponseWriter, r *http.Request)
	// Serve audio file
	// (GET /files/{uuid}/{filename})
	GetFilesUuidFilename(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID, filename string)
	// List all podcast episodes
	// (GET /v1/episodes)
	GetV1Episodes(w http.ResponseWriter, r *http.Request, params GetV1EpisodesParams)
	// Upload a new podcast episode
	// (POST /v1/episodes)
	PostV1Episodes(w http.ResponseWriter, r *http.Request)
	// Delete a podcast episode
	// (DELETE /v1/episodes/{uuid})
	DeleteV1EpisodesUuid(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Redirect to RSS feed
// (GET /)
func (_ Unimplemented) GetRoot(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get iTunes-compatible RSS feed
// (GET /feed.xml)
func (_ Unimplemented) GetFeedXml(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Serve audio file
// (GET /files/{uuid}/{filename})
func (_ Unimplemented) GetFilesUuidFilename(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID, filename string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all podcast episodes
// (GET /v1/episodes)
func (_ Unimplemented) GetV1Episodes(w http.ResponseWriter, r *http.Request, params GetV1EpisodesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload a new podcast episode
// (POST /v1/episodes)
func (_ Unimplemented) PostV1Episodes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a podcast episode
// (DELETE /v1/episodes/{uuid})
func (_ Unimplemented) DeleteV1EpisodesUuid(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetRoot operation middleware
func (siw *ServerInterfaceWrapper) GetRoot(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoot(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFeedXml operation middleware
func (siw *ServerInterfaceWrapper) GetFeedXml(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFeedXml(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFilesUuidFilename operation middleware
func (siw *ServerInterfaceWrapper) GetFilesUuidFilename(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	// ------------- Path parameter "filename" -------------
	var filename string

	err = runtime.BindStyledParameterWithOptions("simple", "filename", chi.URLParam(r, "filename"), &filename, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filename", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFilesUuidFilename(w, r, uuid, filename)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1Episodes operation middleware
func (siw *ServerInterfaceWrapper) GetV1Episodes(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1EpisodesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1Episodes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV1Episodes operation middleware
func (siw *ServerInterfaceWrapper) PostV1Episodes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1Episodes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteV1EpisodesUuid operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1EpisodesUuid(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteV1EpisodesUuid(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/", wrapper.GetRoot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/feed.xml", wrapper.GetFeedXml)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/files/{uuid}/{filename}", wrapper.GetFilesUuidFilename)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/episodes", wrapper.GetV1Episodes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/episodes", wrapper.PostV1Episodes)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/episodes/{uuid}", wrapper.DeleteV1EpisodesUuid)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xX227jNhD9FYLtQ1sosd3Nvvit2U22AbJtmktRYBEEtDhyZlckFV6ycQP/ezGUZF0d",
	"N8U2yIshmZzhmTkzh6NHnhpVGA3aOz5/5C69BSXi41GBzkigx8KaAqxHiAsi+Ftj6UmCSy0WHo3m89qA",
	"VesJ96sC+Jw7b1Ev+TrhqQXhQd4IP7R+R2toNPOowHmhCp7wzFhFm7kUHvZoZcxtx9E2VO1/x3wEG4+/",
	"cZC6oZf31TJDzRykRkvXeEHtYQmW3GSYw40WCoYufre4RC1yRntY3DOCIzpw+PeIg2OyoyUCsVh5GIeg",
	"UMFN+Xffw8eTj0csLo2cXITFDaV5aHYWFjmmZfxxx78lxqPPYTsl5fKIXQgoh2ZXGu8CMJSgPWYIto0j",
	"mgxcrRNu4S6gBcnnnzabqnO7JbGJv81im5B2aju1fL051yw+Q+ophCNryx7p9k5adVQvIbSZxbWRbChw",
	"Tiy3mtXLu4Kv3Nfbh6DJAHVmhgf9enl5xhzYe7DMG6aEFktghZGpcJ5BSadjX9HfMhEkGhaK3AiZMAk5",
	"eEhYjs4n7OKPU/TAFHghhResAOvQedApJJVhbA46CvUyYUJLhpdBg9sjnRIeFzmwSQYg9x9UvuFyzj8Y",
	"dlbhOb+4YIci/QKayL6nM2IU9zPKpilAiwL5nL/Zn+7PiHjhbyM5E/pZQhQnIi1W/Ikk7+DPjfGcMuoK",
	"o13J5pvpbKRbwCpBgsosSLSQespZG/MtCAk2ejg1ZV812ktP8CBUEcPqhNqjNxLmglLCrvicn7dOoxSQ",
	"ZSyCxscT4R0DyL/iMZ0If55Oy7LVHnS0FEVRi8Gk8tkAH0DsiTPvAGuwfwA/wnMvCszBTR6ph9eTR3qj",
	"Dl0/GRSZXAWUx9XuyLYVCnzM/6dHjoSKKoAnvNTtWiWa3vE2QNKKcqfojLrNGgzbXfddXe/mg9pm8lOX",
	"hw3CBWrKcLKbmV827UddcjA9eIL3z65fsd9byPicfzdpxolJNUtMSikcOTJeaNp4lpmg+yVxQXLTEoWy",
	"CO5nk1puniL+z9lRvWvAeO9KFA+ogmI6qAVYZrJGzrxhFnywdDlEPu8CxFxWhOaokCShyYKETITc8/ls",
	"mnBVeqYXekNdvQ3vbCqYLqrfRtG4L1hswWKyzMEWMO3TpyOnXz+r54fcowfldhZBNU2uNwCEtWI1Vhan",
	"6Hw7dLJ5+0xM/6keT7QHSxNaddVBtbFdlhGcyPPB7RdHKONG6vHMuG5BUvuD84dGrnpBqZB7LIT1E+rg",
	"Pboku3F9q0n8uSMz+6HWrB+3Ta1DP42kdM13qtMrGkZ7Q1R3ZIxhjw1S60FLzb5d+dadNCzgOpZqNmUu",
	"pCk4l4U8X5Wq/gJddCgkqyqc7TGFzqFelullxjLU9yJHyVAXIU7KB7O3/z+oK+1CURhLWVEgUcTPILa3",
	"gROrNPL4mtTmKo7RTDANX/uKM7gQq9moLHEau4dS9D7+34jRVTnAvMBMNLxkDp4SHoI5Vr8vMJXUIFqD",
	"ySuqiJJBJkaqgfZFw7E5512wlr5Jyh084cHm9H3B19frfwIAAP//9NZARAUSAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
