// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Episode defines model for Episode.
type Episode struct {
	// Author Episode author
	Author *string `json:"author,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Description Episode description
	Description string `json:"description"`

	// DurationSecs Duration in seconds
	DurationSecs *int `json:"duration_secs,omitempty"`

	// FileName Original file name
	FileName string `json:"file_name"`

	// FileSize File size in bytes
	FileSize int `json:"file_size"`

	// MimeType MIME type
	MimeType string `json:"mime_type"`

	// PubDate Publication date
	PubDate time.Time `json:"pub_date"`

	// Title Episode title
	Title string `json:"title"`

	// Uuid Unique identifier
	Uuid openapi_types.UUID `json:"uuid"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code string `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// GetV1EpisodesParams defines parameters for GetV1Episodes.
type GetV1EpisodesParams struct {
	// Limit Maximum number of episodes to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of episodes to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostV1EpisodesMultipartBody defines parameters for PostV1Episodes.
type PostV1EpisodesMultipartBody struct {
	// Author Episode author
	Author *string `json:"author,omitempty"`

	// Description Episode description (required)
	Description string `json:"description"`

	// File Audio file (required)
	File openapi_types.File `json:"file"`

	// PubDate Publication date
	PubDate *time.Time `json:"pub_date,omitempty"`

	// Title Episode title
	Title *string `json:"title,omitempty"`
}

// PostV1EpisodesMultipartRequestBody defines body for PostV1Episodes for multipart/form-data ContentType.
type PostV1EpisodesMultipartRequestBody PostV1EpisodesMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get iTunes-compatible RSS feed
	// (GET /feed.xml)
	GetFeedXml(w http.ResponseWriter, r *http.Request)
	// Serve audio file
	// (GET /files/{uuid}/{filename})
	GetFilesUuidFilename(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID, filename string)
	// List all podcast episodes
	// (GET /v1/episodes)
	GetV1Episodes(w http.ResponseWriter, r *http.Request, params GetV1EpisodesParams)
	// Upload a new podcast episode
	// (POST /v1/episodes)
	PostV1Episodes(w http.ResponseWriter, r *http.Request)
	// Delete a podcast episode
	// (DELETE /v1/episodes/{uuid})
	DeleteV1EpisodesUuid(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get iTunes-compatible RSS feed
// (GET /feed.xml)
func (_ Unimplemented) GetFeedXml(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Serve audio file
// (GET /files/{uuid}/{filename})
func (_ Unimplemented) GetFilesUuidFilename(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID, filename string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all podcast episodes
// (GET /v1/episodes)
func (_ Unimplemented) GetV1Episodes(w http.ResponseWriter, r *http.Request, params GetV1EpisodesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload a new podcast episode
// (POST /v1/episodes)
func (_ Unimplemented) PostV1Episodes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a podcast episode
// (DELETE /v1/episodes/{uuid})
func (_ Unimplemented) DeleteV1EpisodesUuid(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetFeedXml operation middleware
func (siw *ServerInterfaceWrapper) GetFeedXml(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFeedXml(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetFilesUuidFilename operation middleware
func (siw *ServerInterfaceWrapper) GetFilesUuidFilename(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	// ------------- Path parameter "filename" -------------
	var filename string

	err = runtime.BindStyledParameterWithOptions("simple", "filename", chi.URLParam(r, "filename"), &filename, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filename", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFilesUuidFilename(w, r, uuid, filename)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetV1Episodes operation middleware
func (siw *ServerInterfaceWrapper) GetV1Episodes(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1EpisodesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1Episodes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostV1Episodes operation middleware
func (siw *ServerInterfaceWrapper) PostV1Episodes(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1Episodes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteV1EpisodesUuid operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1EpisodesUuid(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteV1EpisodesUuid(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/feed.xml", wrapper.GetFeedXml)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/files/{uuid}/{filename}", wrapper.GetFilesUuidFilename)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/episodes", wrapper.GetV1Episodes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/episodes", wrapper.PostV1Episodes)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/episodes/{uuid}", wrapper.DeleteV1EpisodesUuid)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xX32/bthP/Vwh+vw/boFT2lr74bWmTLUC7ZUsyDCiCgBZPzrUiqZDHtJ7h/304SrZl",
	"S46XoQvyJpr3+/O543khC2dqZ8FSkJOFDMUdGJU+T2sMTgN/1t7V4AkhXahId87zl4ZQeKwJnZWTlYJo",
	"7zNJ8xrkRAbyaGdymcnCgyLQt4r62m/4Dp0VhAYCKVPLTJbOGxaWWhEc8c2Q2S1D+6Lq/jpkI/rk/jZA",
	"EfpW3rbXAq0IUDirw8YKWoIZeDZTYgW3Vhnom/jV4wytqgTLiCQzEEcyEPCvAQNnrMdXHMR0TjAcgkED",
	"t83Puxben78/FelqwHMdp7dc5r7aRZxWWDT5J4l/CgwhVbAfkuZ6QC9G1H21a4v3EQRqsIQlgu/GkVR6",
	"ppaZ9HAf0YOWkw9rodbvNiXW+XdR7ALSLe0Wl2/Wft30IxTEKZx63/TIdu8UbUftFISFRbobqIaBENRs",
	"r9rq+lDyrfmVeD9oVkBbur6jn6+uLkQA/wBekBNGWTUDUTtdqEACGjiD+Ix0J1TU6ESsK6d0JjRUQJCJ",
	"CgNl4vK3d0ggDJDSipSowQcMBLaArFVMzcGu0M4yoawWeBUthCOeU4pwWoHISwD96oup1lhO5E9OXLTx",
	"/H55KU5U8Qksg/3APlIWD2OupqvBqhrlRP7wavxqxMArukvgbOxOFnIGaUgxeIn555q9AJ0B6D+Taw+h",
	"djY0wH4/GjX4WgKbNFVdr7omb20205W/dqHanWKSk+BwEowhGqP8vAlgoCBbwjmXMOQLJvsyX/CJqbx8",
	"NClWuY6oz1rpVBavDBD4ICcfFhI5Ki6VzGQz4FbttCEZ+QhZJ8uD3TlottzEsN/0rqmbw3gwv/LvtnFY",
	"RzhFyxXODiPz45qnTKfj0fEjuH8MzZO0cfh/D6WcyP/lm3c3bx/dvJkZAy7T5LeOROmi3aXEJfdlp3sa",
	"EjyM81VfPgb8H+PTlVQP8Z23Q31BE42w0UzBC1du+p6c8EDR8xRNeN5HSLVsAa3QIMkuehpKFSuSk/Eo",
	"k6axzAc+oW1P/ceNCbMd1S+D0YRPWO+JxZVlgD3BdL2PBrzfPKnn+9gjgQkHSdCuXct1AMp7NR+ixTsM",
	"1E2ddV4/MaZ/xcdzS+B5lWnfBGgFu7RMwamq6j0TaddwYYCPFy5sE5LbHwKdOD3fScrEirBWnnLu4CN+",
	"Tbbz+lor61N3S/HNamZ9u2+969vZjJRt9YPT6QVtbTvbxvZuldIe2jiWvZYafz36rjqpT+BVLu0SJ0Is",
	"CgihjFU1b6b6M3TRidKiZbg4EgZDQDtryiucF2gfVIVaoK1jWimPx6//+6CubYh17TxXxYBGlf4viKN1",
	"OImlCceXNG2u074plLDweXfi9B7EdjdqKM77aX8UvU2/b4bRdbPAPMNO1H9kjh8bPBzmEH+fYStZBdFZ",
	"TF4QIxoEhRpgA8slxaE95030Hiy1pmUmo6/kROZyebP8OwAA///y7OqxLhEAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
