// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: episodes.sql

package queries

import (
	"context"
	"database/sql"
	"time"

	uuid "github.com/google/uuid"
)

const deleteEpisode = `-- name: DeleteEpisode :exec
DELETE FROM episodes
WHERE uuid = ?
`

func (q *Queries) DeleteEpisode(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEpisode, argUuid)
	return err
}

const getEpisodeByUUID = `-- name: GetEpisodeByUUID :one
SELECT uuid, title, description, author, pub_date, file_path, file_name, file_size, mime_type, duration_secs, created_at FROM episodes
WHERE uuid = ?
LIMIT 1
`

func (q *Queries) GetEpisodeByUUID(ctx context.Context, argUuid uuid.UUID) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeByUUID, argUuid)
	var i Episode
	err := row.Scan(
		&i.Uuid,
		&i.Title,
		&i.Description,
		&i.Author,
		&i.PubDate,
		&i.FilePath,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.DurationSecs,
		&i.CreatedAt,
	)
	return i, err
}

const insertEpisode = `-- name: InsertEpisode :one
INSERT INTO episodes (
  uuid, title, description, author, pub_date, file_path, file_name, file_size, mime_type, duration_secs
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING uuid, title, description, author, pub_date, file_path, file_name, file_size, mime_type, duration_secs, created_at
`

type InsertEpisodeParams struct {
	Uuid         uuid.UUID      `json:"uuid"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Author       sql.NullString `json:"author"`
	PubDate      time.Time      `json:"pub_date"`
	FilePath     string         `json:"file_path"`
	FileName     string         `json:"file_name"`
	FileSize     int64          `json:"file_size"`
	MimeType     string         `json:"mime_type"`
	DurationSecs int64          `json:"duration_secs"`
}

func (q *Queries) InsertEpisode(ctx context.Context, arg InsertEpisodeParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, insertEpisode,
		arg.Uuid,
		arg.Title,
		arg.Description,
		arg.Author,
		arg.PubDate,
		arg.FilePath,
		arg.FileName,
		arg.FileSize,
		arg.MimeType,
		arg.DurationSecs,
	)
	var i Episode
	err := row.Scan(
		&i.Uuid,
		&i.Title,
		&i.Description,
		&i.Author,
		&i.PubDate,
		&i.FilePath,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.DurationSecs,
		&i.CreatedAt,
	)
	return i, err
}

const listAllEpisodes = `-- name: ListAllEpisodes :many
SELECT uuid, title, description, author, pub_date, file_path, file_name, file_size, mime_type, duration_secs, created_at FROM episodes
ORDER BY pub_date DESC
`

func (q *Queries) ListAllEpisodes(ctx context.Context) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, listAllEpisodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.Uuid,
			&i.Title,
			&i.Description,
			&i.Author,
			&i.PubDate,
			&i.FilePath,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.DurationSecs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllValidEpisodes = `-- name: ListAllValidEpisodes :many
SELECT uuid, title, description, author, pub_date, file_path, file_name, file_size, mime_type, duration_secs, created_at FROM episodes
WHERE duration_secs > 0
ORDER BY pub_date DESC
`

func (q *Queries) ListAllValidEpisodes(ctx context.Context) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, listAllValidEpisodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.Uuid,
			&i.Title,
			&i.Description,
			&i.Author,
			&i.PubDate,
			&i.FilePath,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.DurationSecs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodes = `-- name: ListEpisodes :many
SELECT uuid, title, description, author, pub_date, file_path, file_name, file_size, mime_type, duration_secs, created_at FROM episodes
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListEpisodesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListEpisodes(ctx context.Context, arg ListEpisodesParams) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.Uuid,
			&i.Title,
			&i.Description,
			&i.Author,
			&i.PubDate,
			&i.FilePath,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.DurationSecs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodesPendingDuration = `-- name: ListEpisodesPendingDuration :many
SELECT uuid, title, description, author, pub_date, file_path, file_name, file_size, mime_type, duration_secs, created_at FROM episodes WHERE duration_secs = 0
`

func (q *Queries) ListEpisodesPendingDuration(ctx context.Context) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodesPendingDuration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.Uuid,
			&i.Title,
			&i.Description,
			&i.Author,
			&i.PubDate,
			&i.FilePath,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.DurationSecs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidEpisodes = `-- name: ListValidEpisodes :many
SELECT uuid, title, description, author, pub_date, file_path, file_name, file_size, mime_type, duration_secs, created_at FROM episodes
WHERE duration_secs > 0
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListValidEpisodesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListValidEpisodes(ctx context.Context, arg ListValidEpisodesParams) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, listValidEpisodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.Uuid,
			&i.Title,
			&i.Description,
			&i.Author,
			&i.PubDate,
			&i.FilePath,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.DurationSecs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEpisodeDuration = `-- name: UpdateEpisodeDuration :exec
UPDATE episodes SET duration_secs = ? WHERE uuid = ?
`

type UpdateEpisodeDurationParams struct {
	DurationSecs int64     `json:"duration_secs"`
	Uuid         uuid.UUID `json:"uuid"`
}

func (q *Queries) UpdateEpisodeDuration(ctx context.Context, arg UpdateEpisodeDurationParams) error {
	_, err := q.db.ExecContext(ctx, updateEpisodeDuration, arg.DurationSecs, arg.Uuid)
	return err
}
