// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"time"

	uuid "github.com/google/uuid"
)

type Episode struct {
	Uuid         uuid.UUID      `json:"uuid"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Author       sql.NullString `json:"author"`
	PubDate      time.Time      `json:"pub_date"`
	FilePath     string         `json:"file_path"`
	FileName     string         `json:"file_name"`
	FileSize     int64          `json:"file_size"`
	MimeType     string         `json:"mime_type"`
	DurationSecs int64          `json:"duration_secs"`
	CreatedAt    time.Time      `json:"created_at"`
}
