// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	DeleteEpisode(ctx context.Context, argUuid uuid.UUID) error
	GetEpisodeByUUID(ctx context.Context, argUuid uuid.UUID) (Episode, error)
	InsertEpisode(ctx context.Context, arg InsertEpisodeParams) (Episode, error)
	ListAllEpisodes(ctx context.Context) ([]Episode, error)
	ListAllValidEpisodes(ctx context.Context) ([]Episode, error)
	ListEpisodes(ctx context.Context, arg ListEpisodesParams) ([]Episode, error)
	ListEpisodesPendingDuration(ctx context.Context) ([]Episode, error)
	ListValidEpisodes(ctx context.Context, arg ListValidEpisodesParams) ([]Episode, error)
	UpdateEpisodeDuration(ctx context.Context, arg UpdateEpisodeDurationParams) error
}

var _ Querier = (*Queries)(nil)
